# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  default:
    external:
      name: netcan

services:
  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "9984:5984"
    networks:
      - default

  CVMadrid.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb4

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "10984:5984"
    networks:
      - default

  CVAndalucia.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb5

  couchdb6:
    container_name: couchdb6
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "11984:5984"
    networks:
      - default

  CVAragon.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb6

  couchdb7:
    container_name: couchdb7
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "12984:5984"
    networks:
      - default

  CVAsturias.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb7:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb7

  couchdb8:
    container_name: couchdb8
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "13984:5984"
    networks:
      - default

  CVIllesBalears.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb8:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb8

  couchdb9:
    container_name: couchdb9
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "14984:5984"
    networks:
      - default

  CVCanarias.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb9:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb9

  couchdb10:
    container_name: couchdb10
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "15984:5984"
    networks:
      - default

  CVCantabria.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb10:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb10

  couchdb11:
    container_name: couchdb11
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "16984:5984"
    networks:
      - default

  CVCastillayLeon.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb11

  couchdb12:
    container_name: couchdb12
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "17984:5984"
    networks:
      - default

  CVCastillalaMancha.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb12

  couchdb13:
    container_name: couchdb13
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "18984:5984"
    networks:
      - default

  CVCataluna.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb13:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb13

  couchdb14:
    container_name: couchdb14
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "19984:5984"
    networks:
      - default

  CVComunitatValenciana.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb14:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb14

  couchdb15:
    container_name: couchdb15
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "20984:5984"
    networks:
      - default

  CVExtremadura.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb15:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb15

  couchdb16:
    container_name: couchdb16
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "21984:5984"
    networks:
      - default

  CVGalicia.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb16:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb16

  couchdb17:
    container_name: couchdb17
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "22984:5984"
    networks:
      - default

  CVMurcia.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb17:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb17

  couchdb18:
    container_name: couchdb18
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "23984:5984"
    networks:
      - default

  CVNavarra.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb18:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb18

  couchdb19:
    container_name: couchdb19
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "24984:5984"
    networks:
      - default

  CVPaisVasco.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb19:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb19

  couchdb20:
    container_name: couchdb20
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "25984:5984"
    networks:
      - default

  CVLaRioja.colegiosveterinarios.netcan.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb20:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb20