-- --------------------------------------------------------
-- Host:                         tfm.cnhygfwtvffy.eu-west-3.rds.amazonaws.com
-- Versión del servidor:         10.4.8-MariaDB-log - Source distribution
-- SO del servidor:              Linux
-- HeidiSQL Versión:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla CARGA_INICIAL_BlockChain.__RAZAS_GRUPOS
CREATE TABLE IF NOT EXISTS `__RAZAS_GRUPOS` (
  `ID_RAZA` int(11) NOT NULL,
  `NOMBRE_RAZA` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `ID_GRUPO` int(11) DEFAULT NULL,
  `NOMBRE_GRUPO` varchar(50) COLLATE latin1_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

-- Volcando datos para la tabla CARGA_INICIAL_BlockChain.__RAZAS_GRUPOS: ~346 rows (aproximadamente)
/*!40000 ALTER TABLE `__RAZAS_GRUPOS` DISABLE KEYS */;
INSERT INTO `__RAZAS_GRUPOS` (`ID_RAZA`, `NOMBRE_RAZA`, `ID_GRUPO`, `NOMBRE_GRUPO`) VALUES
	(0, 'Mestizo', 0, 'MESTIZOS'),
	(1, 'Pastor alemán', 1, 'GRUPO 1'),
	(2, 'Australian kelpie', 1, 'GRUPO 1'),
	(3, 'Perro de pastor belga', 1, 'GRUPO 1'),
	(4, 'Schipperke', 1, 'GRUPO 1'),
	(5, 'Perro pastor croata', 1, 'GRUPO 1'),
	(6, 'Perro lobo checoslovaco', 1, 'GRUPO 1'),
	(7, 'Tchuvatch eslovaco', 1, 'GRUPO 1'),
	(8, 'Perro de pastor catalán', 1, 'GRUPO 1'),
	(9, 'Perro de pastor mallorquín', 1, 'GRUPO 1'),
	(10, 'Perro pastor autraliano', 1, 'GRUPO 1'),
	(11, 'Pastor de los Pirineos de cara rasa', 1, 'GRUPO 1'),
	(12, 'Pastor de Beauce', 1, 'GRUPO 1'),
	(13, 'Pastor de Brie', 1, 'GRUPO 1'),
	(14, 'Pastor de Picardía', 1, 'GRUPO 1'),
	(15, 'Perro pastor de los Prineos de pelo largo', 1, 'GRUPO 1'),
	(16, 'Komondor', 1, 'GRUPO 1'),
	(17, 'Kuvasz', 1, 'GRUPO 1'),
	(18, 'Mudi', 1, 'GRUPO 1'),
	(19, 'Puli', 1, 'GRUPO 1'),
	(20, 'Pumi', 1, 'GRUPO 1'),
	(21, 'Pastor bergamasco', 1, 'GRUPO 1'),
	(22, 'Perro de pastor de la Maremma y de los Abruzos', 1, 'GRUPO 1'),
	(23, 'Pastor holandés', 1, 'GRUPO 1'),
	(24, 'Perro lobo de Saarloos', 1, 'GRUPO 1'),
	(25, 'Schapendoes neerlandés', 1, 'GRUPO 1'),
	(26, 'Perro de pastor polcao de las llanuras', 1, 'GRUPO 1'),
	(27, 'Perro pastor polaco de Podhale', 1, 'GRUPO 1'),
	(28, 'Perro de pastor portugués', 1, 'GRUPO 1'),
	(29, 'Antiguo perro de pastor inglés', 1, 'GRUPO 1'),
	(30, 'Border collie', 1, 'GRUPO 1'),
	(31, 'Collie barbudo', 1, 'GRUPO 1'),
	(32, 'Collie de pelo corto', 1, 'GRUPO 1'),
	(33, 'Collie de pelo largo', 1, 'GRUPO 1'),
	(34, 'Perro pastor de Shetland', 1, 'GRUPO 1'),
	(35, 'Welsh corgi cardigan', 1, 'GRUPO 1'),
	(36, 'Welsh corgi pembroke', 1, 'GRUPO 1'),
	(37, 'Perro de pastor rumano de los Cárpatos', 1, 'GRUPO 1'),
	(38, 'Perro pastor rumano de Mioritza', 1, 'GRUPO 1'),
	(39, 'Perro de pastor de Rusia Meriodonal', 1, 'GRUPO 1'),
	(40, 'Pastor blanco suizo', 1, 'GRUPO 1'),
	(41, 'Boyero australiano', 1, 'GRUPO 1'),
	(42, 'Boyero de las Ardenas', 1, 'GRUPO 1'),
	(43, 'Boyero de Flandes', 1, 'GRUPO 1'),
	(44, 'Affenpinscher', 2, 'GRUPO 2'),
	(45, 'Dobermann', 2, 'GRUPO 2'),
	(46, 'Pinscher alemán', 2, 'GRUPO 2'),
	(47, 'Pinscher miniatura', 2, 'GRUPO 2'),
	(48, 'Pinscher austriaco', 2, 'GRUPO 2'),
	(49, 'Schnauzer', 2, 'GRUPO 2'),
	(50, 'Schnauzer gigante', 2, 'GRUPO 2'),
	(51, 'Schnauzer miniatura', 2, 'GRUPO 2'),
	(52, 'Perro smous holandés', 2, 'GRUPO 2'),
	(53, 'Terrier ruso negro', 2, 'GRUPO 2'),
	(54, 'Perro corso italiano', 2, 'GRUPO 2'),
	(55, 'Bóxer', 2, 'GRUPO 2'),
	(56, 'Gran danés', 2, 'GRUPO 2'),
	(57, 'Rotweiler', 2, 'GRUPO 2'),
	(58, 'Dogo argentino', 2, 'GRUPO 2'),
	(59, 'Fila brasileño', 2, 'GRUPO 2'),
	(60, 'Shar pei', 2, 'GRUPO 2'),
	(61, 'Broholmer', 2, 'GRUPO 2'),
	(62, 'Perro dogo mallorquín', 2, 'GRUPO 2'),
	(63, 'Dogo canario', 2, 'GRUPO 2'),
	(64, 'Dogo de Burdeos', 2, 'GRUPO 2'),
	(65, 'Mastín napolitano', 2, 'GRUPO 2'),
	(66, 'Tosa', 2, 'GRUPO 2'),
	(67, 'Fila de San Miguel', 2, 'GRUPO 2'),
	(68, 'Bulldog', 2, 'GRUPO 2'),
	(69, 'Bullmastiff', 2, 'GRUPO 2'),
	(70, 'Mastiff', 2, 'GRUPO 2'),
	(71, 'Hovawart', 2, 'GRUPO 2'),
	(72, 'Leonberger', 2, 'GRUPO 2'),
	(73, 'Landseer tipo europeo continental', 2, 'GRUPO 2'),
	(74, 'Perro de pastor de Anatolia', 2, 'GRUPO 2'),
	(75, 'Terranova', 2, 'GRUPO 2'),
	(76, 'Pastor de Karst', 2, 'GRUPO 2'),
	(77, 'Mastín del Pirineo', 2, 'GRUPO 2'),
	(78, 'Mastín español', 2, 'GRUPO 2'),
	(79, 'Perro de montaña de los Pirineos', 2, 'GRUPO 2'),
	(80, 'Perro de pastor yugoslavo de Charplanina', 2, 'GRUPO 2'),
	(81, 'Perro de montaña del Atlas', 2, 'GRUPO 2'),
	(82, 'Perro de Castro Laboreiro', 2, 'GRUPO 2'),
	(83, 'Perro de la Sierra de la Estrela', 2, 'GRUPO 2'),
	(84, 'Rafeiro del Alentejo', 2, 'GRUPO 2'),
	(85, 'Perro pastor de Asia Central', 2, 'GRUPO 2'),
	(86, 'Perro pastor del Cáucaso', 2, 'GRUPO 2'),
	(87, 'Perro San Bernardo', 2, 'GRUPO 2'),
	(88, 'Dogo del Tibet', 2, 'GRUPO 2'),
	(89, 'Boyero de Montana Bernes', 2, 'GRUPO 2'),
	(90, 'Gran boyero suizo', 2, 'GRUPO 2'),
	(91, 'Perro boyero de Appenzell', 2, 'GRUPO 2'),
	(92, 'Perro boyero de Entlebuch', 2, 'GRUPO 2'),
	(93, 'Terrier cazador alemán', 3, 'GRUPO 3'),
	(94, 'Terrier brasileño', 3, 'GRUPO 3'),
	(95, 'Kerly blue terrier', 3, 'GRUPO 3'),
	(96, 'Soft coated wheaten terrier irlandés', 3, 'GRUPO 3'),
	(97, 'Terrier glen de imaal irlandés', 3, 'GRUPO 3'),
	(98, 'Terrier irlandés', 3, 'GRUPO 3'),
	(99, 'Airedale terrier', 3, 'GRUPO 3'),
	(100, 'Bedlington terrier', 3, 'GRUPO 3'),
	(101, 'Border terrier', 3, 'GRUPO 3'),
	(102, 'Fox terrier de pelo alambre', 3, 'GRUPO 3'),
	(103, 'Fox terrier de pelo liso', 3, 'GRUPO 3'),
	(104, 'Lakeland terrier', 3, 'GRUPO 3'),
	(105, 'Manchester terrier', 3, 'GRUPO 3'),
	(106, 'Parson russell terrier', 3, 'GRUPO 3'),
	(107, 'Welsh terrier', 3, 'GRUPO 3'),
	(108, 'Australian terrier', 3, 'GRUPO 3'),
	(109, 'Terrier japonés', 3, 'GRUPO 3'),
	(110, 'Cairn terrier', 3, 'GRUPO 3'),
	(111, 'Dandie dimmont terrier', 3, 'GRUPO 3'),
	(112, 'Nerfolk terrier', 3, 'GRUPO 3'),
	(113, 'Norwich terrier', 3, 'GRUPO 3'),
	(114, 'Scottish terrier', 3, 'GRUPO 3'),
	(115, 'Sealyham terrier', 3, 'GRUPO 3'),
	(116, 'Skye terrier', 3, 'GRUPO 3'),
	(117, 'Jack russell terrier', 3, 'GRUPO 3'),
	(118, 'West highland white terrier', 3, 'GRUPO 3'),
	(119, 'Terrier checo', 3, 'GRUPO 3'),
	(120, 'American staffordshire terrier', 3, 'GRUPO 3'),
	(121, 'Bull terrier', 3, 'GRUPO 3'),
	(122, 'Bull terrier miniatura', 3, 'GRUPO 3'),
	(123, 'Staffordshire bull terrier', 3, 'GRUPO 3'),
	(124, 'Terrier sedoso australiano', 3, 'GRUPO 3'),
	(125, 'Terrier inglés toy', 3, 'GRUPO 3'),
	(126, 'Yorkshire terrier', 3, 'GRUPO 3'),
	(127, 'Dachshund estándar', 4, 'GRUPO 4'),
	(128, 'Dachshund miniatura', 4, 'GRUPO 4'),
	(129, 'Teckel para la caza del conejo', 4, 'GRUPO 4'),
	(130, 'Husky siberiano', 5, 'GRUPO 5'),
	(131, 'Malamute de Alaska', 5, 'GRUPO 5'),
	(132, 'Perro de Groenlandia', 5, 'GRUPO 5'),
	(133, 'Samoyedo', 5, 'GRUPO 5'),
	(134, 'Perro de osos de Carelia', 5, 'GRUPO 5'),
	(135, 'Spitz finlandés', 5, 'GRUPO 5'),
	(136, 'Cazador de alces noruego gris', 5, 'GRUPO 5'),
	(137, 'Cazador de alces noruego negro', 5, 'GRUPO 5'),
	(138, 'Lundehund noruego', 5, 'GRUPO 5'),
	(139, 'Laika de Siberia Occidental', 5, 'GRUPO 5'),
	(140, 'Laika de Siberia Oriental', 5, 'GRUPO 5'),
	(141, 'Laika ruso-europeo', 5, 'GRUPO 5'),
	(142, 'Perro cazador de alces sueco', 5, 'GRUPO 5'),
	(143, 'Spitz norrbotten', 5, 'GRUPO 5'),
	(144, 'Pastor finlandés de Laponia', 5, 'GRUPO 5'),
	(145, 'Perro finlandés de Laponia', 5, 'GRUPO 5'),
	(146, 'Perro de pastor islandés', 5, 'GRUPO 5'),
	(147, 'Behund noruego', 5, 'GRUPO 5'),
	(148, 'Perro sueco de Lapnia', 5, 'GRUPO 5'),
	(149, 'Spitz de los Visigodos - Vallhund sueco', 5, 'GRUPO 5'),
	(150, 'Spitz alemán', 5, 'GRUPO 5'),
	(151, 'Volpino italiano', 5, 'GRUPO 5'),
	(152, 'Eurásico', 5, 'GRUPO 5'),
	(153, 'Chow chow', 5, 'GRUPO 5'),
	(154, 'Akita', 5, 'GRUPO 5'),
	(155, 'Akita americano', 5, 'GRUPO 5'),
	(156, 'Hokkaido', 5, 'GRUPO 5'),
	(157, 'Kai', 5, 'GRUPO 5'),
	(158, 'Kishu', 5, 'GRUPO 5'),
	(159, 'Shiba', 5, 'GRUPO 5'),
	(160, 'Shikoku', 5, 'GRUPO 5'),
	(161, 'Spitz japonés', 5, 'GRUPO 5'),
	(162, 'Korea jindo dog', 5, 'GRUPO 5'),
	(163, 'Basenji', 5, 'GRUPO 5'),
	(164, 'Canaan dog', 5, 'GRUPO 5'),
	(165, 'Perro del faraón', 5, 'GRUPO 5'),
	(166, 'Xoloitzcuintle', 5, 'GRUPO 5'),
	(167, 'Perro sin pelo del Perú', 5, 'GRUPO 5'),
	(168, 'Podenco canario', 5, 'GRUPO 5'),
	(169, 'Podenco ibicenco', 5, 'GRUPO 5'),
	(170, 'Cirneco de Etna', 5, 'GRUPO 5'),
	(171, 'Podenco portugués', 5, 'GRUPO 5'),
	(172, 'Thai ridgeback dog', 5, 'GRUPO 5'),
	(173, 'Perro de Taiwán', 5, 'GRUPO 5'),
	(174, 'Chien de Saint Hubert', 6, 'GRUPO 6'),
	(175, 'American foxhound', 6, 'GRUPO 6'),
	(176, 'Perro negro y fuego para la caza del mapache', 6, 'GRUPO 6'),
	(177, 'Billy', 6, 'GRUPO 6'),
	(178, 'Gascon saintongeois', 6, 'GRUPO 6'),
	(179, 'Gran grifon vendeano', 6, 'GRUPO 6'),
	(180, 'Gran sabueso anglo-francés blanco y naranja', 6, 'GRUPO 6'),
	(181, 'Gran sabueso anglo-francés blanco y negro', 6, 'GRUPO 6'),
	(182, 'Gran sabueso anglo-francés tricolor', 6, 'GRUPO 6'),
	(183, 'Gran sabueso azul de Gascuña', 6, 'GRUPO 6'),
	(184, 'Sabueso francés blanco y naranja', 6, 'GRUPO 6'),
	(185, 'Sabueso francés blanco y negro', 6, 'GRUPO 6'),
	(186, 'Sabueso francés tricolor', 6, 'GRUPO 6'),
	(187, 'Sabueso polaco', 6, 'GRUPO 6'),
	(188, 'Foxhound inglés', 6, 'GRUPO 6'),
	(189, 'Perro de Nutria', 6, 'GRUPO 6'),
	(190, 'Sabueso austriaco negro y fuego', 6, 'GRUPO 6'),
	(191, 'Sabueso de Tirol', 6, 'GRUPO 6'),
	(192, 'Sabueso estirio de pelo áspero', 6, 'GRUPO 6'),
	(193, 'Sabueso de Bosnia de pelo cerdoso', 6, 'GRUPO 6'),
	(194, 'Sabueso de Istria de pelo corto', 6, 'GRUPO 6'),
	(195, 'Sabueso de Istria de pelo duro', 6, 'GRUPO 6'),
	(196, 'Sabueso del Valle de Save', 6, 'GRUPO 6'),
	(197, 'Sabueso eslovaco', 6, 'GRUPO 6'),
	(198, 'Sabueso español', 6, 'GRUPO 6'),
	(199, 'Sabueso finlandés', 6, 'GRUPO 6'),
	(200, 'Beagle-Harrier', 6, 'GRUPO 6'),
	(201, 'Briquet grifon vendeano', 6, 'GRUPO 6'),
	(202, 'Grifón azul de Gascuña', 6, 'GRUPO 6'),
	(203, 'Grifón del Nivernais', 6, 'GRUPO 6'),
	(204, 'Grifón leonado de Bretaña', 6, 'GRUPO 6'),
	(205, 'Pequeño sabueso azul de Gascuña', 6, 'GRUPO 6'),
	(206, 'Porcelane', 6, 'GRUPO 6'),
	(207, 'Sabueso anglo-francés de tamaño mediano', 6, 'GRUPO 6'),
	(208, 'Sabueso artesiano', 6, 'GRUPO 6'),
	(209, 'Sabueso del Ariege', 6, 'GRUPO 6'),
	(210, 'Sabueso poitevin', 6, 'GRUPO 6'),
	(211, 'Sabueso helénico', 6, 'GRUPO 6'),
	(212, 'Sabueso de Transilvania', 6, 'GRUPO 6'),
	(213, 'Sabueso italiano de pelo duro', 6, 'GRUPO 6'),
	(214, 'Sabueso italiano de pelo raso', 6, 'GRUPO 6'),
	(215, 'Sabueso de montaña del Montenegro', 6, 'GRUPO 6'),
	(216, 'Sabueso de Hygen', 6, 'GRUPO 6'),
	(217, 'Sabueso de Halden', 6, 'GRUPO 6'),
	(218, 'Sabueso noruego', 6, 'GRUPO 6'),
	(219, 'Harrier', 6, 'GRUPO 6'),
	(220, 'Sabueso serbio', 6, 'GRUPO 6'),
	(221, 'Sabueso tricolor serbio', 6, 'GRUPO 6'),
	(222, 'Sabueso de Småland', 6, 'GRUPO 6'),
	(223, 'Sabueso de Hamilton', 6, 'GRUPO 6'),
	(224, 'Sabueso schiller', 6, 'GRUPO 6'),
	(225, 'Sabueso suizo', 6, 'GRUPO 6'),
	(226, 'Perro tejonero de Westfalia', 6, 'GRUPO 6'),
	(227, 'Sabueso alemán', 6, 'GRUPO 6'),
	(228, 'Basset artesiano de Normandía', 6, 'GRUPO 6'),
	(229, 'Basset azul de Gascuña', 6, 'GRUPO 6'),
	(230, 'Basset leonado de Bretaña', 6, 'GRUPO 6'),
	(231, 'Gran basset grifón vendeano', 6, 'GRUPO 6'),
	(232, 'Pequeño basset grifón vendeano', 6, 'GRUPO 6'),
	(233, 'Basset hound', 6, 'GRUPO 6'),
	(234, 'Beagle', 6, 'GRUPO 6'),
	(235, 'Perro tejonero sueco', 6, 'GRUPO 6'),
	(236, 'Sabueso suizo pequeño', 6, 'GRUPO 6'),
	(237, 'Rastreador de Hannover', 6, 'GRUPO 6'),
	(238, 'Rastreador montañés de Baviera', 6, 'GRUPO 6'),
	(239, 'Dachsbracke de los Alpes', 6, 'GRUPO 6'),
	(240, 'Dálmata', 6, 'GRUPO 6'),
	(241, 'Perro crestado rodesiano', 6, 'GRUPO 6'),
	(242, 'Braco alemán de pelo corto', 7, 'GRUPO 7'),
	(243, 'Perro de muestra alemán de pelo cerdoso', 7, 'GRUPO 7'),
	(244, 'Perro de muestra alemán de pelo duro', 7, 'GRUPO 7'),
	(245, 'Pudelpointer', 7, 'GRUPO 7'),
	(246, 'Weimaraner', 7, 'GRUPO 7'),
	(247, 'Antiguo perro de muestra danés', 7, 'GRUPO 7'),
	(248, 'Braco eslovaco de pelo duro', 7, 'GRUPO 7'),
	(249, 'Perdiguero de Burgos', 7, 'GRUPO 7'),
	(250, 'Braco de Auvernia', 7, 'GRUPO 7'),
	(251, 'Braco de Airege', 7, 'GRUPO 7'),
	(252, 'Braco del Borbonesado', 7, 'GRUPO 7'),
	(253, 'Braco francés - Tipo Gascuña', 7, 'GRUPO 7'),
	(254, 'Braco francés - Tipo Pirineos', 7, 'GRUPO 7'),
	(255, 'Braco Saint-Germain', 7, 'GRUPO 7'),
	(256, 'Braco húngaro de pelo corto', 7, 'GRUPO 7'),
	(257, 'Braco húngaro de pelo duro', 7, 'GRUPO 7'),
	(258, 'Braco italiano', 7, 'GRUPO 7'),
	(259, 'Perdiguero portugués', 7, 'GRUPO 7'),
	(260, 'Deutsch langhaar', 7, 'GRUPO 7'),
	(261, 'Gran münsterländer', 7, 'GRUPO 7'),
	(262, 'Pequeño münsterländer', 7, 'GRUPO 7'),
	(263, 'Spaniel azul de Picardia', 7, 'GRUPO 7'),
	(264, 'Spaniel bretón', 7, 'GRUPO 7'),
	(265, 'Spaniel de Font-Audemer', 7, 'GRUPO 7'),
	(266, 'Spaniel francés', 7, 'GRUPO 7'),
	(267, 'Spaniel picardo', 7, 'GRUPO 7'),
	(268, 'Prediguero de Drente', 7, 'GRUPO 7'),
	(269, 'Perdiguero frisón', 7, 'GRUPO 7'),
	(270, 'Grifón de muestra de pelo duro', 7, 'GRUPO 7'),
	(271, 'Espinone', 7, 'GRUPO 7'),
	(272, 'Grifón de muestra bohemio de pelo duro', 7, 'GRUPO 7'),
	(273, 'Pointer inglés', 7, 'GRUPO 7'),
	(274, 'Setter irlandés rojo', 7, 'GRUPO 7'),
	(275, 'Setter irlandés rojo y blanco', 7, 'GRUPO 7'),
	(276, 'Setter gordon', 7, 'GRUPO 7'),
	(277, 'Setter inglés', 7, 'GRUPO 7'),
	(278, 'Perro cobrador de Nueva Escocia', 8, 'GRUPO 8'),
	(279, 'Chesapeake bay retriever', 8, 'GRUPO 8'),
	(280, 'Cobrador de pelo liso', 8, 'GRUPO 8'),
	(281, 'Cobrador de pelo rizado', 8, 'GRUPO 8'),
	(282, 'Cobrador dorado', 8, 'GRUPO 8'),
	(283, 'Labrador retriever', 8, 'GRUPO 8'),
	(284, 'Perdiguero alemán', 8, 'GRUPO 8'),
	(285, 'American cocker spaniel', 8, 'GRUPO 8'),
	(286, 'Nederlandse kooikerhondje', 8, 'GRUPO 8'),
	(287, 'Clumber spaniel', 8, 'GRUPO 8'),
	(288, 'Cocker spaniel inglés', 8, 'GRUPO 8'),
	(289, 'Field spaniel', 8, 'GRUPO 8'),
	(290, 'Springer spaniel galés', 8, 'GRUPO 8'),
	(291, 'Springer spaniel inglés', 8, 'GRUPO 8'),
	(292, 'Sussex spaniel', 8, 'GRUPO 8'),
	(293, 'Perro de agua español', 8, 'GRUPO 8'),
	(294, 'Perro de agua americano', 8, 'GRUPO 8'),
	(295, 'Perro de agua francés', 8, 'GRUPO 8'),
	(296, 'Perro de agua irlandés', 8, 'GRUPO 8'),
	(297, 'Perro de agua de Romagna', 8, 'GRUPO 8'),
	(298, 'Perro de agua frisón', 8, 'GRUPO 8'),
	(299, 'Perro de agua portugués', 8, 'GRUPO 8'),
	(300, 'Bichón de pelo rizado', 9, 'GRUPO 9'),
	(301, 'Bichón maltés', 9, 'GRUPO 9'),
	(302, 'Bichón habanero', 9, 'GRUPO 9'),
	(303, 'Bichón boloñés', 9, 'GRUPO 9'),
	(304, 'Coton de Tulea', 9, 'GRUPO 9'),
	(305, 'Pequeño perro león', 9, 'GRUPO 9'),
	(306, 'Caniche', 9, 'GRUPO 9'),
	(307, 'Grifón belga (Bégica)', 9, 'GRUPO 9'),
	(308, 'Grifon bruxellois', 9, 'GRUPO 9'),
	(309, 'Petit brabançon', 9, 'GRUPO 9'),
	(310, 'Perro crestado chino', 9, 'GRUPO 9'),
	(311, 'Lhasa apso', 9, 'GRUPO 9'),
	(312, 'Shih tzu', 9, 'GRUPO 9'),
	(313, 'Spaniel tibetano', 9, 'GRUPO 9'),
	(314, 'Terrier tibetano', 9, 'GRUPO 9'),
	(315, 'Cavalier charles spaniel', 9, 'GRUPO 9'),
	(316, 'King charles spaniel', 9, 'GRUPO 9'),
	(317, 'Pekinés', 9, 'GRUPO 9'),
	(318, 'Spaniel japonés', 9, 'GRUPO 9'),
	(319, 'Pug', 9, 'GRUPO 9'),
	(320, 'Boston terrier', 9, 'GRUPO 9'),
	(321, 'Bulldog francés', 9, 'GRUPO 9'),
	(322, 'Chihuahua', 9, 'GRUPO 9'),
	(323, 'Spaniel continental enano de compañía', 9, 'GRUPO 9'),
	(324, 'Kromfohrländer', 9, 'GRUPO 9'),
	(325, 'Lebrel afgano', 10, 'GRUPO 10'),
	(326, 'Saluki', 10, 'GRUPO 10'),
	(327, 'Lebrel ruso para la caza', 10, 'GRUPO 10'),
	(328, 'Lebrel irlandés', 10, 'GRUPO 10'),
	(329, 'Lebrel escocés', 10, 'GRUPO 10'),
	(330, 'Galgo español', 10, 'GRUPO 10'),
	(331, 'Lebrel húngaro', 10, 'GRUPO 10'),
	(332, 'Pequeño lebrel italiano', 10, 'GRUPO 10'),
	(333, 'Azawakh', 10, 'GRUPO 10'),
	(334, 'Sloughi', 10, 'GRUPO 10'),
	(335, 'Lebrel polcao', 10, 'GRUPO 10'),
	(336, 'Greyhound', 10, 'GRUPO 10'),
	(337, 'Whippet', 10, 'GRUPO 10'),
	(338, 'Hai Bangkaew dog', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(339, 'Perro de pastor de Europa del Sureste', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(340, 'Perro de granja danés y sueco', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(341, 'Pastor de Bosnia y Herzegovina', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(342, 'Gonczy polsky', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(343, 'Cimarrón uruguayo', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(344, 'Perro ruso toy', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE'),
	(345, 'Pastor australiano stumpy tail', 999, 'GRUPO RAZAS ACEPTADAS PROVISIONALMENTE');
/*!40000 ALTER TABLE `__RAZAS_GRUPOS` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
