-- --------------------------------------------------------
-- Host:                         tfm.cnhygfwtvffy.eu-west-3.rds.amazonaws.com
-- Versión del servidor:         10.4.8-MariaDB-log - Source distribution
-- SO del servidor:              Linux
-- HeidiSQL Versión:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para procedimiento CARGA_INICIAL_BlockChain._generar_TABLA_PERSONAS
DELIMITER //
CREATE PROCEDURE `_generar_TABLA_PERSONAS`(
	IN `p_numeroPersonas` INT
)
BEGIN

	DECLARE dni INT;

	DROP TABLE IF EXISTS __NOMBRES_personas;

	CREATE TABLE __NOMBRES_personas as
	SELECT NOMBRE, "HOMBRE" as SEXO
	FROM __NOMBRES_hombres 
	UNION ALL
	SELECT NOMBRE, "MUJER" as SEXO
	FROM __NOMBRES_mujeres;

	TRUNCATE TABLE PERSONAS;

	INSERT INTO PERSONAS (NOMBRE, APELLIDO_1, APELLIDO_2, SEXO, TIPO_DOCUMENTO, IDENTIFICADOR_DOCUMENTO, PAIS_EMISOR)	VALUES
			( "CRISTINA", "RODRIGUEZ", "CHAMORRO", "MUJER", 	"NIF", "00000010X", "SPAIN" ),
			( "DANIEL", "LANZAS", "PELLICO", "HOMBRE", 			"NIF", "93649739H", "SPAIN"  ), 
			( "HELENA", "GARCIA", "FERNANDEZ", "MUJER", 			"NIF", "01937444Q", "SPAIN" ),
			( "JOSE", "BENNANI", "PAREJA", "HOMBRE", 				"NIF", "00099322P", "SPAIN" ),
			( "JUAN JOSE", "LUCAS", "DE LA FUENTE", "HOMBRE", 	"NIF", "00012375R", "SPAIN" ),
			( "UNAI", "ARES", "ICARAN", "HOMBRE", 					"NIF", "30624315E", "SPAIN" ), 
			( "PILAR", "SANTOS", "PEÑAS", "MUJER", 				"NIF", "03080483R", "SPAIN"  ),
			( "SERGIO", "TORRES", "PALOMINO", "HOMBRE", 			"NIF", "96969643X", "SPAIN" ),
			( "JOSE CARLOS", "SOTO", "GOMEZ", "HOMBRE", 			"NIF", "62444456P", "SPAIN" );

	FOR numeroRegistros IN 10..p_numeroPersonas
	DO
		SET dni = ( SELECT FLOOR(1 + (RAND() * 99999999)));

		INSERT INTO PERSONAS (NOMBRE, APELLIDO_1, APELLIDO_2, SEXO,
									  TIPO_DOCUMENTO, IDENTIFICADOR_DOCUMENTO, PAIS_EMISOR )
		SELECT NOMBRE.NOMBRE, APELLIDO_1.APELLIDO AS APELLIDO_1, APELLIDO_2.APELLIDO AS APELLIDO_2, NOMBRE.SEXO,
				 "NIF", IDENTIFICADOR_DOCUMENTO.NIF, "SPAIN"
		FROM 	
			( SELECT NOMBRE, SEXO FROM __NOMBRES_personas ORDER BY RAND() LIMIT 1) AS NOMBRE,
			( SELECT APELLIDO FROM __APELLIDOS_personas ORDER BY RAND() LIMIT 1) AS APELLIDO_1,
			( SELECT APELLIDO FROM __APELLIDOS_personas ORDER BY RAND() LIMIT 1) AS APELLIDO_2,
			( SELECT CONCAT( CAST(dni AS CHAR) , SUBSTR("TRWAGMYFPDXBNJZSQVHLCKE", MOD(dni, 23) + 1, 1)) as NIF) AS IDENTIFICADOR_DOCUMENTO;
			
	END FOR;	
	
	SELECT * FROM PERSONAS;
END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
