-- --------------------------------------------------------
-- Host:                         tfm.cnhygfwtvffy.eu-west-3.rds.amazonaws.com
-- Versión del servidor:         10.4.8-MariaDB-log - Source distribution
-- SO del servidor:              Linux
-- HeidiSQL Versión:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para procedimiento CARGA_INICIAL_BlockChain._generar_TABLA_MICROCHIPS_perros
DELIMITER //
CREATE PROCEDURE `_generar_TABLA_MICROCHIPS_perros`()
BEGIN
 
  # FALTARIA DETERMINAR QUE PERSONAS SON VETERINARIOS
  
	TRUNCATE TABLE MICROCHIPS_perros;	
	
	INSERT INTO MICROCHIPS_perros ( ID_PERRO, ID_VETERINARIO, COD_MICROCHIP, FECHA_ALTA, FECHA_BAJA)
	SELECT  ID AS ID_PERRO	
			, ( SELECT ID FROM PERSONAS WHERE ID BETWEEN 100 AND 120 ORDER BY RAND() LIMIT 1 ) AS ID_VETERINARIO	
			, ( SELECT LPAD (FLOOR(1 + (RAND() * 1000000000000000)),15,'0') ) AS COD_MICROCHIP	
			, PERROS.FECHA_NACIMIENTO + INTERVAL 45 + 90 * RAND() DAY AS FECHA_ALTA
			, NULL AS FECHA_BAJA
	FROM 	PERROS
	WHERE	FECHA_NACIMIENTO IS NOT NULL
	ORDER BY ID; 
	
	SELECT * FROM MICROCHIPS_perros;
END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
